platform :ios, '16.0'

# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

use_frameworks! :linkage => :static
use_modular_headers!

target 'HolaMed' do
  config = use_native_modules!

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,   # This is enough, + env flag above
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
